<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit970afca05c66920bdf7f82116f590d54
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\Process\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
    );

    public static $prefixesPsr0 = array (
        'K' => 
        array (
            'Knp\\Snappy' => 
            array (
                0 => __DIR__ . '/..' . '/knplabs/knp-snappy/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit970afca05c66920bdf7f82116f590d54::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit970afca05c66920bdf7f82116f590d54::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit970afca05c66920bdf7f82116f590d54::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
